name: Build
on:
  pull_request:
    branches: '*'
  push:
    branches: '1-add-ci-cd'
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
#      - uses: actions/checkout@v1
#      - name: set up JDK 11
      - name: set up JDK 18
#        uses: actions/setup-java@v1
        uses: actions/setup-java@v4
        with:
          java-version: 1.11
      - name: Maven Package
        run: mvn -B clean package -DskipTests